/* Generated by cbindgen from masterbus-ffi. Do not edit by hand. */

#ifndef MASTERBUS_H
#define MASTERBUS_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Operational status of a device.
 */
typedef enum {
    MbStatus_Offline = 0,
    MbStatus_Sleeping = 1,
    MbStatus_On = 2,
    MbStatus_OnWarning = 3,
    MbStatus_OffFault = 4,
    MbStatus_OffError = 5,
    MbStatus_Updating = 6,
    MbStatus_Unknown = 7,
} MbStatus;

/**
 * Discriminant of an [`MbValue`].
 */
typedef enum {
    MbValueType_Float = 0,
    MbValueType_Date = 1,
    MbValueType_Time = 2,
    MbValueType_Boolean = 3,
    MbValueType_List = 4,
    MbValueType_Text = 5,
    MbValueType_DeviceRef = 6,
    MbValueType_Eventable = 7,
    MbValueType_Invalid = 8,
} MbValueType;

/**
 * Opaque connection handle.
 */
typedef struct MbBus MbBus;

/**
 * Opaque decoded value.
 */
typedef struct MbValue MbValue;

/**
 * Calendar date (mirrors `masterbus::Date`).
 */
typedef struct {
    int32_t day;
    int32_t mon;
    int32_t year;
} MbDate;

/**
 * Clock / duration (mirrors `masterbus::Time`).
 */
typedef struct {
    int32_t sec;
    int32_t min;
    int32_t hour;
    uint32_t days;
} MbTime;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open a SocketCAN connection (Linux only; returns NULL elsewhere).
 *
 * `cache_dir` may be NULL (memory-only) or a directory for the schema cache.
 */
MbBus *mb_open_socketcan(const char *iface, const char *cache_dir);

/**
 * Close and free a bus handle.
 */
void mb_close(MbBus *bus);

/**
 * Fill `*out_ids` with the ids of every device on the bus and return the count
 * (waits up to ~2 s for the broadcast list to fill). Returns -1 on error.
 * Free the array with [`mb_free_ids`].
 */
int32_t mb_devices(MbBus *bus, uint32_t **out_ids);

/**
 * Free an id array returned by [`mb_devices`].
 */
void mb_free_ids(uint32_t *ids, int32_t len);

/**
 * Device product name (NULL on error). Free with [`mb_free_str`].
 */
char *mb_device_name(MbBus *bus, uint32_t id);

/**
 * Device article number (NULL on error). Free with [`mb_free_str`].
 */
char *mb_device_article(MbBus *bus, uint32_t id);

/**
 * Device serial number (NULL on error). Free with [`mb_free_str`].
 */
char *mb_device_serial(MbBus *bus, uint32_t id);

/**
 * Device revision code (NULL on error). Free with [`mb_free_str`].
 */
char *mb_device_revision(MbBus *bus, uint32_t id);

/**
 * Device firmware version (NULL on error). Free with [`mb_free_str`].
 */
char *mb_device_firmware(MbBus *bus, uint32_t id);

/**
 * Device operational status.
 */
MbStatus mb_device_status(MbBus *bus, uint32_t id);

/**
 * Number of monitoring groups on a device (-1 on error).
 */
int32_t mb_group_count(MbBus *bus, uint32_t id);

/**
 * Name of the `group_index`-th monitoring group (NULL on error).
 */
char *mb_group_name(MbBus *bus, uint32_t id, int32_t group_index);

/**
 * Fill `*out_fields` with the field indices of the `group_index`-th monitoring
 * group; returns the count (-1 on error). Free with [`mb_free_fields`].
 */
int32_t mb_group_fields(MbBus *bus, uint32_t id, int32_t group_index, int32_t **out_fields);

/**
 * Free a field-index array returned by [`mb_group_fields`].
 */
void mb_free_fields(int32_t *fields, int32_t len);

/**
 * Field name (NULL on error). Free with [`mb_free_str`].
 */
char *mb_field_name(MbBus *bus, uint32_t id, int32_t field);

/**
 * Field unit, possibly empty (NULL on error). Free with [`mb_free_str`].
 */
char *mb_field_unit(MbBus *bus, uint32_t id, int32_t field);

/**
 * Whether a field is currently writable (false on error).
 */
bool mb_field_writable(MbBus *bus, uint32_t id, int32_t field);

/**
 * Read a field's current value (NULL on error). Free with [`mb_free_value`].
 */
MbValue *mb_field_value(MbBus *bus, uint32_t id, int32_t field);

/**
 * Write a boolean and return the value observed afterwards (NULL on error /
 * rejected write). Free with [`mb_free_value`].
 */
MbValue *mb_set_bool(MbBus *bus, uint32_t id, int32_t field, bool value);

/**
 * Write a float and return the value observed afterwards (NULL on error /
 * rejected write). Free with [`mb_free_value`].
 */
MbValue *mb_set_float(MbBus *bus, uint32_t id, int32_t field, float value);

/**
 * Discriminant of a value.
 */
MbValueType mb_value_type(const MbValue *v);

/**
 * Float payload (0.0 if not a float).
 */
float mb_value_float(const MbValue *v);

/**
 * Boolean payload (false if not a boolean).
 */
bool mb_value_bool(const MbValue *v);

/**
 * Date payload (day=-1 if not a date).
 */
MbDate mb_value_date(const MbValue *v);

/**
 * Time payload (sec=-1 if not a time).
 */
MbTime mb_value_time(const MbValue *v);

/**
 * Text payload (NULL if not text). Free with [`mb_free_str`].
 */
char *mb_value_text(const MbValue *v);

/**
 * Selected index for list/enum/device-ref/eventable values (-1 otherwise).
 */
int32_t mb_value_list_index(const MbValue *v);

/**
 * Number of options/entries for list/eventable/device-ref values (0 otherwise).
 */
int32_t mb_value_list_size(const MbValue *v);

/**
 * Label of the `index`-th option of a list/eventable value (NULL otherwise).
 * Free with [`mb_free_str`].
 */
char *mb_value_list_label(const MbValue *v, int32_t index);

/**
 * Referenced device id at `index` for a device-ref value (0 otherwise).
 */
uint32_t mb_value_device_id(const MbValue *v, int32_t index);

/**
 * Free a value returned by `mb_field_value` / `mb_set_*`.
 */
void mb_free_value(MbValue *v);

/**
 * Free a string returned by any `mb_*` function.
 */
void mb_free_str(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MASTERBUS_H */
