//! Offline string-table catalog — a discovery accelerator.
//!
//! A device serves its string table four characters per CAN round trip (opcode
//! `0x30`, see PROTOCOL §4.4). A device reporting a few hundred strings — an
//! MLI Ultra reports ~400 — costs on the order of a thousand exchanges, and
//! that dominates first-time discovery. But the static half of every device's
//! table is baked into the vendor firmware and is identical for every unit of a
//! given `(article, firmware)`, so it can be recovered offline and shipped here.
//! See FINDINGS §4.6.
//!
//! **The runtime spot-check is the correctness guarantee, not the key.** Before
//! trusting a bundled table we fetch a few ids live and compare (three round
//! trips instead of a thousand); only on a full match do we serve the rest from
//! the table. So a stale or wrong entry degrades to a live fetch — never to a
//! wrong string. The bundled data is generated and validated id-for-id against
//! a live 14-device bus by `tools/gen_runtime.py`.
//!
//! Only ids in a model's verified span are bundled, and only where the firmware
//! holds real static text. Sub-article EEPROM ids (serial, user-assigned name,
//! switch labels) and runtime-generated strings are never bundled — those are
//! always fetched live.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

/// The bundled catalog, validated against the reference bus. Compact JSON so
/// it can be regenerated by `tools/gen_runtime.py` and diffed in review.
const CATALOG_JSON: &str = include_str!("strings/catalog.json");

/// One firmware build's static string table for a device model.
#[derive(Debug, Deserialize)]
pub struct FirmwareEntry {
    /// Firmware version string, as [`DeviceIdentity::firmware`] reports it
    /// (`"major.minor"`, e.g. `"2.14"`).
    ///
    /// [`DeviceIdentity::firmware`]: crate::model::DeviceIdentity::firmware
    pub firmware: String,
    /// The device's `StringVersion` when this table was captured. Recorded for
    /// provenance and future cache-keying; the live spot-check, not this field,
    /// is what gates trust (the wire selector for `StringVersion` isn't
    /// confirmed yet — see PROTOCOL §4.3).
    #[serde(default)]
    pub string_version: u32,
    /// A few ids spread across the span, fetched live and compared before the
    /// table is trusted. Chosen at generation time to be static and (for
    /// multi-language models) language-distinguishing.
    pub spot_check: Vec<u16>,
    /// Wire string id → static text, for the device's served language, over the
    /// verified span only.
    #[serde(deserialize_with = "de_string_map")]
    pub strings: HashMap<u16, String>,
}

/// Deserialize a `{ "34": "text", ... }` object into `HashMap<u16, String>`
/// (JSON object keys are always strings).
fn de_string_map<'de, D>(d: D) -> Result<HashMap<u16, String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let raw: HashMap<String, String> = HashMap::deserialize(d)?;
    raw.into_iter()
        .map(|(k, v)| k.parse::<u16>().map(|k| (k, v)).map_err(serde::de::Error::custom))
        .collect()
}

#[derive(Debug, Deserialize)]
struct Catalog {
    /// Article number → firmware builds known for it.
    articles: HashMap<String, Vec<FirmwareEntry>>,
}

fn catalog() -> &'static Catalog {
    static CATALOG: OnceLock<Catalog> = OnceLock::new();
    CATALOG.get_or_init(|| {
        serde_json::from_str(CATALOG_JSON).expect("bundled string catalog is valid JSON")
    })
}

/// Candidate firmware entries for an article, best match first: the exact
/// firmware-version match (if any) precedes the rest. Empty when the article is
/// not in the catalog. The caller must still spot-check the winner live.
pub fn candidates(article: &str, firmware: &str) -> Vec<&'static FirmwareEntry> {
    let Some(entries) = catalog().articles.get(article) else {
        return Vec::new();
    };
    let mut out: Vec<&'static FirmwareEntry> = entries.iter().collect();
    // Stable sort: exact firmware match sorts first, order otherwise preserved.
    out.sort_by_key(|e| e.firmware != firmware);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_parses_and_has_expected_models() {
        let c = catalog();
        // The reference-bus models bundled by tools/gen_runtime.py.
        for article in ["77010310", "77030900", "66025000"] {
            assert!(c.articles.contains_key(article), "missing {article}");
        }
    }

    #[test]
    fn easyview_static_strings_present_eeprom_excluded() {
        let e = &candidates("77010310", "2.14")[0];
        // Static UI strings are served…
        assert_eq!(e.strings.get(&34).map(String::as_str), Some("77010310"));
        assert_eq!(e.strings.get(&212).map(String::as_str), Some("Factory reset"));
        // …but sub-article EEPROM ids (below the table start) are not bundled,
        // so a misaligned boundary read can't leak in (FINDINGS §4.6).
        assert!(!e.strings.contains_key(&18));
        assert!(e.strings.keys().all(|&id| id >= 34));
    }

    #[test]
    fn candidates_prefer_exact_firmware() {
        // Present article, unknown firmware: still offered (spot-check decides),
        // but a firmware match would sort ahead of it.
        let c = candidates("66025000", "9.9");
        assert_eq!(c.len(), 1);
        assert_eq!(candidates("66025000", "1.4")[0].firmware, "1.4");
        // Unknown article: no candidates.
        assert!(candidates("00000000", "1.0").is_empty());
    }

    #[test]
    fn spot_check_ids_are_within_the_bundled_strings() {
        for article in ["77010310", "77030900", "66025000"] {
            let e = &candidates(article, "")[0];
            assert!(!e.spot_check.is_empty());
            for id in &e.spot_check {
                assert!(e.strings.contains_key(id), "{article}: spot id {id} not in table");
            }
        }
    }
}
